[ActiveSupport PAR]
; Global primary clocks
GLOBAL_PRIMARY_USED = 1;
; Global primary clock #0
GLOBAL_PRIMARY_0_SIGNALNAME = Clk96xC;
GLOBAL_PRIMARY_0_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_0_LOADNUM = 372;
; # of global secondary clocks
GLOBAL_SECONDARY_USED = 8;
; Global secondary clock #0
GLOBAL_SECONDARY_0_SIGNALNAME = NN22Control_main_inst/CfgFSMSRegxDP_1_RNISQU51[7];
GLOBAL_SECONDARY_0_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_0_LOADNUM = 14;
GLOBAL_SECONDARY_0_SIGTYPE = CE;
; Global secondary clock #1
GLOBAL_SECONDARY_1_SIGNALNAME = PllLockxS;
GLOBAL_SECONDARY_1_DRIVERTYPE = PLL;
GLOBAL_SECONDARY_1_LOADNUM = 29;
GLOBAL_SECONDARY_1_SIGTYPE = RST;
; Global secondary clock #2
GLOBAL_SECONDARY_2_SIGNALNAME = NN22Control_main_inst/aux_adc_rx_inst/N_109_i;
GLOBAL_SECONDARY_2_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_2_LOADNUM = 26;
GLOBAL_SECONDARY_2_SIGTYPE = CE;
; Global secondary clock #3
GLOBAL_SECONDARY_3_SIGNALNAME = NN22Control_main_inst.aux_adc_rx_inst.ADCSregxDN_0_0_sqmuxa;
GLOBAL_SECONDARY_3_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_3_LOADNUM = 13;
GLOBAL_SECONDARY_3_SIGTYPE = CE;
; Global secondary clock #4
GLOBAL_SECONDARY_4_SIGNALNAME = NN22Control_main_inst/un1_CfgStatexDP_4_sn;
GLOBAL_SECONDARY_4_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_4_LOADNUM = 13;
GLOBAL_SECONDARY_4_SIGTYPE = CE;
; Global secondary clock #5
GLOBAL_SECONDARY_5_SIGNALNAME = NN22Control_main_inst/ext_fifo_inst/ExtFIFOWrAddrxDPe;
GLOBAL_SECONDARY_5_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_5_LOADNUM = 12;
GLOBAL_SECONDARY_5_SIGTYPE = CE;
; Global secondary clock #6
GLOBAL_SECONDARY_6_SIGNALNAME = NN22Control_main_inst/ext_fifo_inst/ExtFIFORdAddrxDPe;
GLOBAL_SECONDARY_6_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_6_LOADNUM = 12;
GLOBAL_SECONDARY_6_SIGTYPE = CE;
; Global secondary clock #7
GLOBAL_SECONDARY_7_SIGNALNAME = NN22Control_main_inst/ext_fifo_inst/N_204_i;
GLOBAL_SECONDARY_7_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_7_LOADNUM = 12;
GLOBAL_SECONDARY_7_SIGTYPE = CE;
; I/O Bank 0 Usage
BANK_0_USED = 20;
BANK_0_AVAIL = 51;
BANK_0_VCCIO = 3.3V;
BANK_0_VREF1 = NA;
; I/O Bank 1 Usage
BANK_1_USED = 29;
BANK_1_AVAIL = 52;
BANK_1_VCCIO = 3.3V;
BANK_1_VREF1 = NA;
; I/O Bank 2 Usage
BANK_2_USED = 45;
BANK_2_AVAIL = 52;
BANK_2_VCCIO = 3.3V;
BANK_2_VREF1 = NA;
; I/O Bank 3 Usage
BANK_3_USED = 15;
BANK_3_AVAIL = 16;
BANK_3_VCCIO = 3.3V;
BANK_3_VREF1 = NA;
; I/O Bank 4 Usage
BANK_4_USED = 14;
BANK_4_AVAIL = 16;
BANK_4_VCCIO = 3.3V;
BANK_4_VREF1 = NA;
; I/O Bank 5 Usage
BANK_5_USED = 17;
BANK_5_AVAIL = 20;
BANK_5_VCCIO = 3.3V;
BANK_5_VREF1 = NA;
