M48
; DRILL file KiCad 10.0.5-10.0.5~ubuntu24.04.1 date 2026-08-25T13:16:48
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-25T13:16:48-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5-10.0.5~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
%
G90
G05
T1
X175.933Y-90.729
X175.933Y-119.279
M30
